-- EbayPrice Phase 1: initial Supabase schema + RLS
-- Paste into Supabase SQL editor (Dashboard > SQL Editor) and run once.
-- Tables are created IF NOT EXISTS so the script is idempotent.

create extension if not exists pgcrypto;

-- ==============================================================
-- User-owned tables (RLS: user_id = auth.uid())
-- ==============================================================

create table if not exists public.sold_orders (
    user_id        uuid not null references auth.users(id) on delete cascade,
    order_id       text not null,
    item_id        text not null,
    sale_date      date,
    buyer          text,
    item_title     text,
    quantity       integer,
    item_price     numeric(10,2),
    shipping       numeric(10,2),
    order_total    numeric(10,2),
    total_fees     numeric(10,2),
    order_earnings numeric(10,2),
    sku            text,
    card           text,
    primary key (user_id, order_id, item_id)
);

create table if not exists public.active_listings (
    user_id             uuid not null references auth.users(id) on delete cascade,
    item_id             text not null,
    title               text,
    card                text,
    condition           text,
    sku                 text,
    price               numeric(10,2),
    shipping_charge     numeric(10,2),
    ad_rate             numeric(5,2),
    watchers            integer,
    days_listed         integer,
    start_date          date,
    quantity            integer,
    estimated_fees      numeric(10,2),
    estimated_net       numeric(10,2),
    recent_sold_avg     numeric(10,2),
    price_vs_sold_avg   numeric(10,2),
    recent_sold_count   integer,
    last_checked        date,
    active_avg_top5     numeric(10,2),
    price_accuracy      numeric(10,4),
    search_position     integer,
    primary key (user_id, item_id)
);

create table if not exists public.inventory_value_history (
    user_id        uuid not null references auth.users(id) on delete cascade,
    snapshot_date  date not null,
    total_value    numeric(12,2),
    total_listings integer,
    primary key (user_id, snapshot_date)
);

create table if not exists public.listing_positions (
    user_id        uuid not null references auth.users(id) on delete cascade,
    item_id        text not null,
    snapshot_date  date not null,
    card_query     text,
    position       integer,
    search_size    integer,
    primary key (user_id, item_id, snapshot_date)
);

create table if not exists public.ebay_connections (
    user_id            uuid primary key references auth.users(id) on delete cascade,
    ebay_user_id       text,
    refresh_token      text,
    scopes             text,
    token_issued_at    timestamptz,
    token_expires_at   timestamptz,
    last_synced_at     timestamptz,
    sync_status        text
);

-- ==============================================================
-- Shared tables (RLS: any authenticated user can SELECT)
-- ==============================================================

create table if not exists public.price_snapshots (
    id             bigint generated by default as identity primary key,
    card_query     text not null,
    snapshot_date  date not null,
    sample_size    integer,
    avg_price      numeric(12,2),
    median_price   numeric(12,2),
    min_price      numeric(12,2),
    max_price      numeric(12,2),
    std_dev        numeric(12,4),
    weighted_avg   numeric(12,2),
    unique (card_query, snapshot_date)
);

create table if not exists public.active_price_snapshots (
    id             bigint generated by default as identity primary key,
    card_query     text not null,
    snapshot_date  date not null,
    sample_size    integer,
    avg_price      numeric(12,2),
    min_price      numeric(12,2),
    max_price      numeric(12,2),
    unique (card_query, snapshot_date)
);

create table if not exists public.sold_listings (
    id            bigint generated by default as identity primary key,
    item_id       text unique,
    card_query    text,
    title         text,
    price         numeric(12,2),
    currency      text,
    condition     text,
    listing_type  text,
    sold_date     timestamptz,
    url           text,
    pulled_at     timestamptz
);

-- ==============================================================
-- Indexes
-- ==============================================================

create index if not exists idx_sold_orders_sale_date   on public.sold_orders (sale_date);
create index if not exists idx_active_listings_card    on public.active_listings (card);
create index if not exists idx_price_snapshots_card    on public.price_snapshots (card_query, snapshot_date);
create index if not exists idx_active_price_snap_card  on public.active_price_snapshots (card_query, snapshot_date);
create index if not exists idx_sold_listings_card      on public.sold_listings (card_query, sold_date);

-- ==============================================================
-- Row Level Security
-- ==============================================================

alter table public.sold_orders             enable row level security;
alter table public.active_listings         enable row level security;
alter table public.inventory_value_history enable row level security;
alter table public.listing_positions       enable row level security;
alter table public.ebay_connections        enable row level security;
alter table public.price_snapshots         enable row level security;
alter table public.active_price_snapshots  enable row level security;
alter table public.sold_listings           enable row level security;

-- User-owned: owner-only access (backend uses service_role, which bypasses RLS)
create policy "sold_orders_owner_all" on public.sold_orders
    for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy "active_listings_owner_all" on public.active_listings
    for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy "inventory_history_owner_all" on public.inventory_value_history
    for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy "listing_positions_owner_all" on public.listing_positions
    for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy "ebay_connections_owner_all" on public.ebay_connections
    for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());

-- Shared: any authenticated user can read; writes only via service_role
create policy "price_snapshots_read" on public.price_snapshots
    for select to authenticated using (true);
create policy "active_price_snapshots_read" on public.active_price_snapshots
    for select to authenticated using (true);
create policy "sold_listings_read" on public.sold_listings
    for select to authenticated using (true);
