-- EbayPrice Phase 2: durable OAuth state store + background job run history
-- Paste into Supabase SQL editor (Dashboard > SQL Editor) and run once, after 0001.
-- Tables are created IF NOT EXISTS so the script is idempotent.

-- ==============================================================
-- OAuth connect-flow state (replaces the backend's in-memory dict so the
-- eBay connect flow survives process restarts/redeploys and works across
-- multiple backend replicas)
-- ==============================================================

create table if not exists public.ebay_oauth_states (
    state       text primary key,
    user_id     uuid not null references auth.users(id) on delete cascade,
    verifier    text not null,
    created_at  timestamptz not null default now(),
    expires_at  timestamptz not null
);

create index if not exists idx_ebay_oauth_states_expires on public.ebay_oauth_states (expires_at);

alter table public.ebay_oauth_states enable row level security;
-- Service-role-only: no policies for `authenticated` (backend uses service_role, which bypasses RLS).

-- ==============================================================
-- Background job run history (shared price-research job, per-user sync/
-- promotion-boost jobs). Nullable user_id: null means a shared/system job.
-- ==============================================================

create table if not exists public.job_runs (
    id           bigint generated by default as identity primary key,
    job_name     text not null,
    user_id      uuid references auth.users(id) on delete cascade,
    status       text not null,
    started_at   timestamptz not null default now(),
    finished_at  timestamptz,
    detail       jsonb
);

create index if not exists idx_job_runs_name_started on public.job_runs (job_name, started_at desc);

alter table public.job_runs enable row level security;
-- Users can see their own job history plus shared/system job history (user_id is null).
create policy "job_runs_owner_or_shared_select" on public.job_runs
    for select to authenticated using (user_id = auth.uid() or user_id is null);
-- Writes only via service_role (backend), no insert/update policy for `authenticated`.
