-- EbayPrice Phase 3 follow-up: persist individual active/competing marketplace
-- listings researched per card (mirrors sold_listings, which already persists
-- individual sold comps - active listings were previously only ever aggregated
-- into active_price_snapshots and never kept as individual rows).
-- Paste into Supabase SQL editor (Dashboard > SQL Editor) and run once, after 0002.

create table if not exists public.active_market_listings (
    id            bigint generated by default as identity primary key,
    item_id       text unique,
    card_query    text,
    title         text,
    price         numeric(12,2),
    currency      text,
    condition     text,
    listing_type  text,
    url           text,
    pulled_at     timestamptz
);

create index if not exists idx_active_market_listings_card on public.active_market_listings (card_query, pulled_at);

alter table public.active_market_listings enable row level security;
-- Shared marketplace data, same access pattern as sold_listings: any authenticated
-- user can read; writes only via service_role (backend), no insert/update policy
-- for `authenticated`.
create policy "active_market_listings_read" on public.active_market_listings
    for select to authenticated using (true);
