-- EbayPrice: audit log of applied price changes, and the input to the reprice cooldown.
-- Paste into Supabase SQL editor (Dashboard > SQL Editor) and run once, after 0004.
-- Created IF NOT EXISTS so the script is idempotent.

-- ==============================================================
-- Every price revision this app actually applied to a live eBay listing, written
-- by routers/active.py (single-listing edit and the bulk apply flow).
--
-- Two jobs:
--   1. An audit trail. active_listings.price is overwritten in place and the Excel
--      workbook keeps no history either, so before this table there was no record
--      anywhere of what a listing used to cost or when it changed. job_runs logged
--      only per-batch counts.
--   2. The reprice cooldown. suggested_price.py declines to suggest a new price for
--      REPRICE_COOLDOWN_DAYS after a change lands, so the model doesn't keep asking
--      to re-edit a listing whose new price has not had time to prove itself.
--      That is why this records *applied* changes only - a revision eBay rejected
--      must not start a cooldown.
--
-- Deliberately append-only: rows are never updated, and nothing prunes them. The
-- volume is one row per applied change (hundreds a month at this catalog size).
-- ==============================================================

create table if not exists public.price_change_log (
    id          bigint generated by default as identity primary key,
    user_id     uuid not null references auth.users(id) on delete cascade,
    item_id     text not null,
    old_price   numeric(10,2),
    new_price   numeric(10,2) not null,
    source      text,          -- 'single' | 'bulk'
    changed_at  timestamptz not null default now()
);

-- Serves both reads: the cooldown lookup (changed_at >= now() - 5 days, grouped by
-- listing) and the per-listing history shown on the detail page.
create index if not exists idx_price_change_log_user_item
    on public.price_change_log (user_id, item_id, changed_at desc);
create index if not exists idx_price_change_log_changed_at
    on public.price_change_log (changed_at desc);

alter table public.price_change_log enable row level security;
-- User-owned, same shape as listing_positions. Backend writes via service_role,
-- which bypasses RLS; this policy is what lets a user read their own history.
create policy "price_change_log_owner_all" on public.price_change_log
    for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());
