-- EbayPrice: cards owned but not yet listed - where they physically are, how many,
-- and which buying lot they came from.
-- Paste into Supabase SQL editor (Dashboard > SQL Editor) and run once, after 0010.
-- Created IF NOT EXISTS so the script is idempotent.

-- ==============================================================
-- The gap this fills: between "bought a lot" (lots, 0008) and "listed it"
-- (active_listings) there is a physical pile of cards this app could not see at
-- all. Nothing in eBay's data knows about it, so unlike almost every other table
-- here this one is entirely hand-entered and never synced or overwritten.
--
-- That is why it is a surrogate id rather than a natural key: the same card in the
-- same condition can sit in two different boxes, and both rows are real. A listed
-- card is NOT represented here - when something goes up for sale, its row is
-- deleted (or its quantity decremented) and active_listings takes over. There is
-- deliberately no "listed" status flag: two tables claiming to know whether a card
-- is listed is exactly how they end up disagreeing.
--
-- card_query is the same catalog identity string used by active_listings and
-- active_price_snapshots (ebaypricer.cards._fmt_card), which is what lets the page
-- show a cached market value without an eBay call. It is nullable on purpose:
-- sealed product, bulk, and anything the catalog cannot express still belongs in
-- the pile, and those rows simply have no value estimate.
--
-- sku is the lot the cards came from, matching lots.sku - free-text rather than a
-- foreign key, because lots rows only exist once a cost has been entered and a
-- pile is usually catalogued before that happens.
-- ==============================================================

create table if not exists public.inventory (
    id          bigint generated by default as identity primary key,
    user_id     uuid not null references auth.users(id) on delete cascade,
    name        text not null,          -- what it is, as the user would say it
    card_query  text,                   -- catalog identity, when there is one
    set_name    text,
    number      text,
    condition   text,                   -- same vocabulary as suggested_price.CONDITION_MULTIPLIER
    quantity    integer not null default 1,
    location    text,                   -- where it physically is: box, binder, page
    sku         text,                   -- buying lot it came from (lots.sku)
    cost        numeric(10,2),          -- per unit, optional - most piles have no per-card basis
    notes       text,
    created_at  timestamptz not null default now(),
    updated_at  timestamptz not null default now(),
    constraint inventory_quantity_positive check (quantity > 0)
);

-- The two ways the page is read: everything for a user (sorted in SQL), and
-- narrowed to one storage location.
create index if not exists idx_inventory_user on public.inventory (user_id, location);
-- Feeds the per-lot rollup, so a lot's page can count what is still unlisted.
create index if not exists idx_inventory_user_sku on public.inventory (user_id, sku);

alter table public.inventory enable row level security;
-- User-owned, same shape as price_change_log and lots. Backend writes via
-- service_role, which bypasses RLS; this policy is what lets a user read their own.
create policy "inventory_owner_all" on public.inventory
    for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());
