const PRESETS = {
    condition: [
        "Near Mint or better",
        "Mint",
        "Near Mint",
        "Lightly Played",
        "Moderately Played",
        "Heavily Played",
        "Damaged",
        "Ungraded",
    ],
    descTmpl: ["reg"],
    shippingPolicy: [
        "Free ebay standard",
        "Free economy",
        "Flat rate priority",
        "Calculated: USPS Ground",
        "Calculated: USPS Priority",
    ],
    paymentPolicy: [
        "Immediate payment",
        "Pay within 3 days",
        "Pay within 5 days",
        "Pay within 7 days",
    ],
    customLabel: [
        "PSA 10",
        "PSA 9",
        "PSA 8",
        "CGC 10",
        "CGC 9.5",
        "CGC 9",
        "Raw",
        "Ungraded",
    ],
};

const DEFAULTS = {
    condition: "Near Mint or better",
    descriptionTemplate: "reg",
    description: [
        "Shipping & Handling",
        "",
        "All orders are shipped securely in a penny sleeve and top loader.",
        "I ship within 1 business day.",
        "",
        "\u2022 Ships securely in penny sleeve and top loader",
        "\u2022 Fast shipping",
        "\u2022 Smoke free home",
        "\u2022 See photos for condition",
        "",
        "Thanks for checking out my listing!",
    ].join("\n"),
    format: "Buy It Now",
    itemPrice: "",
    customLabel: "",
    paymentPolicy: "Immediate payment",
    shippingPolicy: "Free ebay standard",
    packageWeight: {
        pounds: 0,
        ounces: 1,
    },
    dimensions: {
        length: 11,
        width: 6,
        height: 1,
    },
    promotedRate: 2,
};
