const PRESETS = {
    condition: [
        "Near Mint or better",
        "Mint",
        "Near Mint",
        "Lightly Played",
        "Moderately Played",
        "Heavily Played",
        "Damaged",
        "Ungraded",
    ],
    descTmpl: ["reg"],
    shippingPolicy: [
        "Free ebay standard",
        "Free economy",
        "Flat rate priority",
        "Calculated: USPS Ground",
        "Calculated: USPS Priority",
    ],

    customLabel: [
        "PSA 10",
        "PSA 9",
        "PSA 8",
        "CGC 10",
        "CGC 9.5",
        "CGC 9",
        "Raw",
        "Ungraded",
    ],
};

const DEFAULTS = {
    condition: "Near Mint or better",
    descriptionTemplate: "reg",
    description: [
        "Be sure to use code KLINKSUMMER for 10% off 3 or more cards!",
        "",
        "Shipping & Handling:",
        "",
        "Combine orders for reduced shipping!",
        "",
        "\u2022 Cards under $20 ship via eBay Standard Envelope with tracking",
        "\u2022 $20+ cards ship in bubble mailers with USPS Ground Advantage",
        "\u2022 Each card ships in a penny sleeve + top loader or card saver",
        "\u2022 Orders are packaged securely to prevent bending or damage",
        "",
        "If you have any questions or need more photos, feel free to message me",
        "",
        "Thank you for supporting Klink TCG!",
    ].join("\n"),
    format: "Buy It Now",
    itemPrice: "",
    customLabel: "",
    shippingPolicy: "Free ebay standard",
    packageWeight: {
        pounds: 0,
        ounces: 1,
    },
    dimensions: {
        length: 11,
        width: 6,
        height: 1,
    },
    promotedRate: 2,
};
